### ISSUE TITLE
FoFiX_Careers.md no longer exists

### ISSUE THREAD

**Issue by sticks-stuff** [TheNathannator/GuitarGame_ChartFormats#4]
https://github.com/TheNathannator/GuitarGame_ChartFormats/blob/main/doc/FileFormats/CoreFormats/Song_ini.md links to a 404 page now

**Comment by TheNathannator** [comment]
Oh right, I haven't corrected that yet. I'm restructuring things and moved that to another folder, haven't gotten to the song.ini stuff yet.
